server:
  port: 8761


eureka:
  instance:
    hostname: 192.168.10.232
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
        enable-self-preservation: false
