spring:
  application:
    name: eureka-cluster
    admin:
      jmx-name:
  profiles:
    active: peer2

server:
  port: 8762


eureka:
  instance:
    hostname: peer2 #localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:${server.port}/eureka/
  server:
    enable-self-preservation: false
