spring:
  application:
    name: eureka-cluster
    admin:
      jmx-name:
#  profiles:
#    active: peer1
server:
  port: 5555

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
        enable-self-preservation: false
