mysql:
  ip: localhost
  port: 3306
  username: root
  password: root

redis:
  ip: localhost
  port: 6379
  password: uwb!2018@0511_zl

server:
 port: 11007
# servlet:
#   context-path: /gateway
 tomcat:
   uri-encoding: UTF-8
spring:
  application:
    name: uwb-gateway
  cloud:
    gateway:
      discovery:
       locator:
       #是否与服务发现组件进行结合
         enabled: true
      routes:
#      - id: uwb-resources
#        uri: http://192.168.10.232:80
#        predicates:
#          - Path=/uwb/resources/**
      # Normwal Websocket route
#      - id:uwb-websocket
#        uri: ws://192.168.10.232:80
#        predicates:
#          - Path=/uwb/websocket/**
      - id: uwb-test
        uri: http://test
        predicates:
          - Path=/uwb/test/**
          - Method=GET
        filters:
           - AddRequestHeader=X-Request-Foo, Bar
           - AddRequestParameter=foo, bar
           - PreserveHostHeader
#           - name: Hystrix
#             args:
#                name: fallbackcmd
#                fallbackUri: forward:/incaseoffailureusethis
#           - RewritePath=/consumingserviceendpoint, /backingserviceendpoint
  redis:
    redis:
    database: 6
    host: ${redis.ip}
    port: ${redis.port}
    password: ${redis.password}
    jedis:
      pool:
        max-active: 2000
        max-wait: -1
        max-idle: 50
        min-idle: 0
    timeout: 0
  security:
    user:
      name: admin #默认登录页面的账户
      password: zhilu@2016 #默认登录页面的密码
      roles: admin
  thymeleaf:
  # Enable template caching.
      cache: true
      # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
      # LEGACYHTML5，即声明thymeleaf使用非严格的html
      mode: LEGACYHTML5
      # Template files encoding.
      encoding: UTF-8
      # Content-Type value written to HTTP responses.
      servlet:
        content-type: text/html; charset=utf-8
      # Prefix that gets prepended to view names when building a URL.
      prefix: classpath:/templates/
      # Suffix that gets appended to view names when building a URL.
      suffix: .html
      # Check that the template exists before rendering it.
      check-template: true
      # Check that the templates location exists.
      check-template-location: true
      # Enable Thymeleaf view resolution for Web frameworks.
      enabled: true
#  resources:
#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: /**
#spring.thymeleaf.excluded-view-names= # Comma-separated list of view names that should be excluded from resolution.
#spring.thymeleaf.reactive.max-chunk-size= # Maximum size of data buffers used for writing to the response, in bytes.
#spring.thymeleaf.reactive.media-types= # Media types supported by the view technology.
#spring.thymeleaf.template-resolver-order= # Order of the template resolver in the chain.
#spring.thymeleaf.view-names= # Comma-separated list of view names that can be resolved.
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix:
#  datasource:
#    url: mysql://${mysql.ip}:${mysql.port}/uwb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    username: ${mysql.username}
#    password: ${mysql.password}

eureka:
  server:
    ip: localhost
    port: 5555
  instance:
    ip-address: 192.168.10.197
#    instance-id: ${spring.cloud.client.ip_address}:${spring.application.name}:${server.port}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 60
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true

  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://${eureka.server.ip}:${eureka.server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
#    jmx:
#        exposure:
#          include: "*"
#          exclude: ""

remote:
  home: "http://192.168.10.123:222"
#server.session.cookie.http-only=false

########################################################
###datasource
########################################################
#spring.datasource.url jdbc:mysql://${mysql.ip}:${mysql.port}/uwb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&&useSSL=false
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=${mysql.username}
#spring.datasource.password=${mysql.password}
#spring.datasource.initialSize=5
#spring.datasource.minIdle=5
#spring.datasource.maxActive=20
#spring.datasource.maxWait=60000
#spring.datasource.timeBetweenEvictionRunsMillis=60000
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.validationQuery=SELECT 'x'
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
#spring.datasource.filters=stat,wall,log4j
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#spring.datasource.logSlowSql=true
#spring.datasource.useGlobalDataSourceStat=true
#######################################################
###tk.mybatis
#######################################################
#mapper.mappers=com.zhilutec.common.mappers.MyMapper
#mapper.not-empty=false
#mapper.identity=MYSQL
##mybatis mapper
#mybatis.mapper-locations=classpath:daos/*.xml
#指定配置文件
#mybatis.config-location=classpath:mybatis/config.xml
##mybatis.executorType=simple
#mybatis.type-aliases-package=com.zhilutec.dbs.entities
#mybatis.type-handlers-package=com.zhilutec.dbs.daos
#######################################################
###tpageHelper
#######################################################
#pagehelper.helperDialect=mysql
#pagehelper.reasonable=true
#pagehelper.supportMethodsArguments=true
#pagehelper.params=count=countSql
#mapper:
#  mappers: com.zhilutec.common.mappers.MyMapper
#  not-empty: false
#  identity: MYSQL
#mybatis:
#  mapper-locations: classpath:daos/*.xml
#  config-location: com.zhilutec.dbs.entities
#  type-aliases-package: com.zhilutec.dbs.daos
#  type-handlers-package: com.zhilutec.dbs.daos
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

#######################################################
###logger
#######################################################
#logging.level.tk.mybatis=TRACE
#指定日志配置文件路径
#logging.config=classpath:logback-spring.xml
#mybaits sql show###显示SQL语句部分
#logging.level.com.zhilutec.dbs.daos=warn






