spring:
  application:
    name: eureka-cluster
    admin:
      jmx-name:
  profiles:
    active: peer1

server:
  port: 5555


eureka:
  instance:
    hostname: peer1 #localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:${server.port}/eureka/
  server:
        enable-self-preservation: false